# Spring Cloud Gateway configuration
spring:
  cloud:
    gateway:
      routes:
        - id: client-service
          uri: lb://CLIENTSERVICE
          predicates:
            - Path=/clients/**  # Route for client service
        - id: service-voiture
          uri: lb://SERVICE-VOITURE
          predicates:
            - Path=/voitures/**  # Route for service voiture

  # Placeholder settings for future use (a terminer apres)
  placeholder: value  # Example placeholder for future configurations

# Eureka server configuration
eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eurekaaa/  # URL of the Eureka server
    register-with-eureka: true  # Enable registration with Eureka
    fetch-registry: true  # Fetch registry from Eureka server

# Server configuration
server:
  port: 8888  # Port on which the application will run

# Logging configuration to enable detailed logs
logging:
  level:
    org.springframework: DEBUG  # Enable debug level logging for Spring framework
    org.springframework.web: DEBUG  # Enable debug level logging for Spring web
